apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se-v4
spec:
  hosts:
  #- dummy-v4.example.com
  - dummy.default.svc.cluster.local
  addresses:
  - 240.240.240.255
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  # Expose bookinfo through gateway first.
  - address: 172.18.0.0
    ports:
      http: 80