apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: ghcr.io/yaozengzeng/benchmark:qwen-3-0.6b
        imagePullPolicy: IfNotPresent
        env:
        - name: SGLANG_BENCH_GROUP_MODE
          value: sequential
        - name: SGLANG_BENCH_GROUP_SIZE
          value: "16"
        args:
        - --host
        - "172.236.135.42"
        - --backend
        - "vllm"
        - --port
        - "80"
        - --model
        - "Qwen/Qwen3-0.6B"
        - --tokenizer
        # In restricted network environment, you should pre-download the tokenizer, pack it into the docker image and use the path of downloaded tokenizer as the argument.
        # README shows how to pre-download the tokenizer.
        # - "/root/.cache/huggingface/hub/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-7B/snapshots/916b56a44061fd5cd7d6a8fb632557ed4f724f60/
        - "Qwen/Qwen3-0.6B"
        - --dataset-name
        - "generated-shared-prefix"
        - --gsp-num-groups
        - "16"
        - --gsp-prompts-per-group
        - "16"
        - --gsp-system-prompt-len
        - "6400"
        - --gsp-question-len
        - "256"
        - --gsp-output-len
        - "256"
        - --request-rate
        - "800"
        - --max-concurrency
        - "4"
        # If you don't want to generate new test data every time, you can mount the volume to the cache directory.
        #volumeMounts:
        #  - name: benchmark-cache
        #    mountPath: /root/.cache/sglang/benchmark
      restartPolicy: Never
  backoffLimit: 0  # Don't retry on failure 
