apiVersion: batch/v1
kind: Job
metadata:
  name: sglang-benchmark-job
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: 192.168.0.126
      containers:
      - name: benchmark
        image: ghcr.io/yaozengzeng/sglang-benchmark:qwen-7b
        imagePullPolicy: IfNotPresent
        args: ["--host", "10.96.85.194", "--backend", "vllm", "--port", "80", "--model", "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B", "--tokenizer", "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"]
      restartPolicy: Never
  backoffLimit: 0  # Don't retry on failure 
