apiVersion: batch/v1
kind: Job
metadata:
  name: sglang-benchmark-job
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: 192.168.0.126
      containers:
      - name: benchmark
        image: ghcr.io/yaozengzeng/sglang-benchmark:qwen-7b
        imagePullPolicy: IfNotPresent
        #args: ["--host", "10.96.85.194", "--backend", "vllm", "--port", "80", "--model", "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B", "--tokenizer", "/root/.cache/huggingface/hub/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-7B/snapshots/916b56a44061fd5cd7d6a8fb632557ed4f724f60/"]
        args: ["--host", "10.247.162.18", "--backend", "vllm", "--port", "80", "--model", "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B", "--tokenizer", "/root/.cache/huggingface/hub/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-7B/snapshots/916b56a44061fd5cd7d6a8fb632557ed4f724f60/", "--dataset-name", "generated-shared-prefix", "--gsp-num-groups", "256", "--gsp-prompts-per-group", "16", "--gsp-system-prompt-len", "256", "--gsp-question-len", "2048", "--gsp-output-len", "256", "--request-rate", "800", "--max-concurrency", "300"]
      restartPolicy: Never
  backoffLimit: 0  # Don't retry on failure 
