apiVersion: networking.serving.volcano.sh/v1alpha1
kind: ModelRoute
metadata:
  name: vllm-qwen-06b
  namespace: default
spec:
  modelName: "Qwen/Qwen3-0.6B"
  rules:
    - name: "default"
      targetModels:
        - modelServerName: "vllm-qwen-06b"
