#!/bin/bash

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  addresses:
  # Get from command "docker network inspect -f '{{.IPAM.Config}}' kind"
  - 172.18.0.0-172.18.0.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
