apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-manager
  namespace: test
rules:
- apiGroups: ["agents.x-k8s.io"]
  resources: ["sandboxes"]
  verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-app-sandbox-manager
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sandbox-manager
subjects:
- kind: ServiceAccount
  name: my-app
  namespace: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
